// SingleStep harness for TG68KdotC_Kernel driving it as the Macintosh
// IIvi's 68030 (CPU=2'b11, the kernel's most capable mode; see
// tg68k_tests.v header for the documented 68030-parity gaps).
//
// Layout mirrors iigs_simulation/SingleStepTests/sim_main.cpp:
//   - top owns a 24-bit RAM (16 MiB) backing all CPU accesses
//   - one bus access per clkena_in pulse, dispatched by busstate
//   - per-test: load initial RAM + force PC/SR/regs via VERTOPINTERN paths,
//     run the recorded number of cycles, then compare final state
//
// Register injection paths are TBD — see WIRE-UP NOTES below. Until the
// mangled hierarchical names are confirmed, this binary only verifies that
// reset + free-run is healthy when run with no arguments.

#include <verilated.h>
#include "Vtg68k_tests.h"
#include "Vtg68k_tests__Syms.h"

#include <cstdio>
#include <cstdint>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <vector>
#include <string>
#include <map>
#include <algorithm>

#include "../json.hpp"
using json = nlohmann::json;

// Test bytes (preload/test/ram_init) come from the same header the Mac OS
// bench includes. The JSONL corpus carries state; this header carries the
// program bytes -- they must stay in lockstep (both are regenerated by
// SingleStepTests/gen/mame_cpu_capture.lua).
extern "C" {
#include "../gen/cpu_tests.h"
}

const char* disassemble_68k_ext(unsigned int pc,
                                const unsigned short* opwords,
                                int num_words);

#define VERILATOR_MAJOR_VERSION (VERILATOR_VERSION_INTEGER / 1000000)
#if VERILATOR_MAJOR_VERSION >= 5
  #define VERTOPINTERN top->rootp
#else
  #define VERTOPINTERN top
#endif

// busstate values
static constexpr uint8_t BS_FETCH = 0b00;
static constexpr uint8_t BS_IDLE  = 0b01;
static constexpr uint8_t BS_READ  = 0b10;
static constexpr uint8_t BS_WRITE = 0b11;

vluint64_t main_time = 0;
double sc_time_stamp() { return main_time; }

static Vtg68k_tests* top = nullptr;
static std::vector<uint8_t> ram;  // 16 MiB

static inline uint16_t ram_read16(uint32_t a) {
    a &= 0x00FFFFFE;
    return (uint16_t(ram[a]) << 8) | ram[a + 1];
}

// Disassemble up to 5 words starting at pc, using current RAM contents.
// Returns a pointer to a static buffer owned by the disassembler.
static const char* disasm_at(uint32_t pc) {
    unsigned short words[5] = {0};
    for (int i = 0; i < 5; ++i) words[i] = ram_read16(pc + i * 2);
    return disassemble_68k_ext(pc, words, 5);
}
static inline void ram_write16(uint32_t a, uint16_t v, bool uds, bool lds) {
    a &= 0x00FFFFFE;
    if (uds) ram[a]     = uint8_t(v >> 8);
    if (lds) ram[a + 1] = uint8_t(v & 0xFF);
}

// Service one bus access if the kernel is asserting one. Called while clkena
// is high right after the rising edge of clk.
static void service_bus() {
    const uint8_t bs = top->busstate;
    if (bs == BS_IDLE) return;
    const uint32_t a = top->addr_out;
    if (bs == BS_FETCH || bs == BS_READ) {
        top->data_in = ram_read16(a);
    } else if (bs == BS_WRITE) {
        ram_write16(a, top->data_write, !top->nUDS, !top->nLDS);
    }
}

static void tick(bool clkena = true) {
    top->clkena_in = clkena ? 1 : 0;
    top->clk = 0;
    top->eval();
    main_time++;
    top->clk = 1;
    top->eval();
    if (clkena) service_bus();
    main_time++;
}

static void finish() {
    top->final();
    delete top;
    top = nullptr;
}

int main(int argc, char** argv, char** env) {
    top = new Vtg68k_tests();
    Verilated::commandArgs(argc, argv);
    Verilated::traceEverOn(true);

    ram.assign(0x01000000, 0x00);

    // Reset: assert for several cycles, then release. CPU fetches initial
    // SSP from $000000-3 and initial PC from $000004-7 — leave them at 0
    // for now (kernel will start fetching at $0).
    top->reset = 1;
    top->data_in = 0;
    for (int i = 0; i < 32; ++i) tick();
    top->reset = 0;

    // ---- Helpers for register injection/readback --------------------
    // The ghdl-synthesized regfile is split across two unpacked arrays:
    //   regfile_n1[i] = bits [7:0]   (low byte)
    //   regfile_n2[i] = bits [31:8]  (upper 24 bits)
    // Indices 0..7 = D0..D7, 8..15 = A0..A7.
    auto set_reg = [](int i, uint32_t v) {
        VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n1[i] = v & 0xFF;
        VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n2[i] = (v >> 8) & 0xFFFFFF;
    };
    auto get_reg = [](int i) -> uint32_t {
        uint32_t n1 = VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n1[i];
        uint32_t n2 = VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n2[i];
        return (n2 << 8) | n1;
    };

    // ---- Register-path probe (--probe-regs) ---------------------------
    // Self-test that confirms the verilator-exposed regfile layout
    // (regfile_n1/n2 split) is the same one we use for injection.
    if (argc >= 2 && std::string(argv[1]) == "--probe-regs") {
        // Reset vectors: SSP=$00FFFFF8 at $0, PC=$1000 at $4.
        ram[0x00] = 0x00; ram[0x01] = 0xFF; ram[0x02] = 0xFF; ram[0x03] = 0xF8;
        ram[0x04] = 0x00; ram[0x05] = 0x00; ram[0x06] = 0x10; ram[0x07] = 0x00;
        // MOVE.L D0,(xxx).L $00000200 at $1000:  23C0 0000 0200
        ram[0x1000] = 0x23; ram[0x1001] = 0xC0;
        ram[0x1002] = 0x00; ram[0x1003] = 0x00;
        ram[0x1004] = 0x02; ram[0x1005] = 0x00;
        // STOP #$2700 at $1006: 4E72 2700
        ram[0x1006] = 0x4E; ram[0x1007] = 0x72;
        ram[0x1008] = 0x27; ram[0x1009] = 0x00;

        // Reset.
        top->reset = 1;
        for (int i = 0; i < 32; ++i) tick();
        top->reset = 0;

        // Immediately inject D0 = 0xDEADBEEF before kernel decodes MOVE.L.
        // Verilator splits the 32-bit regfile into two arrays:
        //   regfile_n1[i] = bits [7:0]   (low byte)
        //   regfile_n2[i] = bits [31:8]  (upper 24 bits)
        const uint32_t d0 = 0xDEADBEEFu;
        VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n1[0] = d0 & 0xFF;
        VERTOPINTERN->tg68k_tests__DOT__cpu__DOT__regfile_n2[0] = (d0 >> 8) & 0xFFFFFF;
        std::cerr << "Injected D0 = 0x" << std::hex << d0 << std::dec
                  << " before bus startup\n";

        // Trace bus until the kernel halts (STOP fires) or 200 cycles pass.
        uint32_t last_addr = ~0u;
        for (int i = 0; i < 200; ++i) {
            tick();
            uint32_t a = top->addr_out;
            uint8_t  bs = top->busstate;
            if (bs != 0b01 && (a != last_addr || bs == 0b11)) {
                std::cerr << "  cyc " << std::setw(3) << i
                          << " bs=" << int(bs)
                          << " addr=0x" << std::hex << std::setw(8)
                          << std::setfill('0') << a
                          << " data=0x" << std::setw(4) << top->data_write
                          << std::dec << std::setfill(' ') << "\n";
                last_addr = a;
            }
        }

        uint32_t result = (uint32_t(ram[0x200]) << 24)
                        | (uint32_t(ram[0x201]) << 16)
                        | (uint32_t(ram[0x202]) << 8)
                        |  uint32_t(ram[0x203]);
        std::cerr << "RAM[0x200..0x203] = 0x" << std::hex << std::setw(8)
                  << std::setfill('0') << result << std::dec
                  << (result == 0xDEADBEEF ? " ✓ regfile layout confirmed"
                                           : " ✗ MISMATCH — layout wrong")
                  << "\n";
        finish();
        return result == 0xDEADBEEF ? 0 : 1;
    }

    // ---- JSONL test runner -------------------------------------------
    //
    // Drives the same MAME-derived oracle corpus the Mac II bench uses
    // (SingleStepTests/results/cpu/mame_baseline_2026-06-12.json).
    // Schema: one JSON object per line, with `name`, `initial`, `final`.
    // Each snapshot has d[8], a[8], ccr, ram[64].
    //
    // For each test we plant a small program in RAM and let the kernel
    // execute it:
    //   $1000: MOVE #initial.ccr, CCR  (4 bytes; sets CCR before test)
    //   $1004: test bytes from cpu_tests.h (matched by name)
    //   $....: MOVE CCR,$00001900      (6 bytes; dumps post-test CCR)
    //   $....: STOP #$2700             (4 bytes; halts CPU)
    //   $1800: scratch RAM (64 bytes from initial.ram[])
    // Then inject D0..D7/A0..A7 directly via the regfile, run until we
    // see the MOVE-CCR write to $1900 (which proves the test committed),
    // and compare regs + CCR + scratch RAM with the corpus's `final`.
    const std::string fname = argc >= 2 ? std::string(argv[1])
        : "../results/cpu/mame_baseline_2026-06-12.json";
    std::ifstream f(fname);
    if (!f) { std::cerr << "Cannot open " << fname << "\n"; finish(); return 1; }

    // Build a name -> test-bytes lookup from the same header the Mac
    // bench uses. cpu_tests.h is the authoritative source for the bytes;
    // the JSONL corpus carries only state, not the program.
    std::map<std::string, const CpuTestSpec*> bytes_by_name;
    for (unsigned i = 0; i < CPU_N_TESTS; ++i)
        bytes_by_name[g_cpu_tests[i].name] = &g_cpu_tests[i];

    int passed = 0, failed = 0, skipped = 0;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty()) continue;
        json t = json::parse(line);
        const std::string name = t.value("name", "<unnamed>");
        auto it = bytes_by_name.find(name);
        if (it == bytes_by_name.end()) {
            std::cerr << "SKIP " << name << ": no test bytes in cpu_tests.h\n";
            ++skipped; continue;
        }
        const CpuTestSpec* spec = it->second;
        // privileged tests can run here: the verilator harness boots TG68K
        // with reset vectors planted, so the kernel starts in supervisor
        // mode (S=1, IPL=7). MOVES/MOVE-SR/MOVEC all execute fine.
        // hw_unsafe tests would lock the bench (STOP halts the CPU
        // entirely; RESET asserts /RESET which we don't observe; RTE
        // jumps to an OS-side stack frame we don't have).
        if (spec->hw_unsafe) {
            ++skipped; continue;
        }

        auto& init   = t["initial"];
        auto& final_ = t["final"];

        // Build the test program in RAM.
        std::fill(ram.begin(), ram.end(), 0);

        const uint32_t init_ssp = init["a"][7].get<uint32_t>();
        ram[0] = (init_ssp >> 24) & 0xFF;
        ram[1] = (init_ssp >> 16) & 0xFF;
        ram[2] = (init_ssp >> 8)  & 0xFF;
        ram[3] = (init_ssp)       & 0xFF;
        ram[4] = 0x00; ram[5] = 0x00; ram[6] = 0x10; ram[7] = 0x00;  // PC=$1000

        const uint8_t init_ccr = init["ccr"].get<unsigned>() & 0xFF;
        ram[0x1000] = 0x44; ram[0x1001] = 0xFC;
        ram[0x1002] = 0x00; ram[0x1003] = init_ccr;

        uint32_t pc = 0x1004;
        for (unsigned i = 0; i < spec->test_len; ++i)
            ram[pc + i] = spec->test[i];
        pc += spec->test_len;

        // MOVE CCR,$00001900 -- writes a word: byte 0x1900 = 0, byte 0x1901 = CCR.
        const uint32_t move_ccr_addr = pc;
        ram[pc + 0] = 0x42; ram[pc + 1] = 0xF9;
        ram[pc + 2] = 0x00; ram[pc + 3] = 0x00;
        ram[pc + 4] = 0x19; ram[pc + 5] = 0x00;
        pc += 6;

        // STOP #$2700 -- halts the CPU; bus goes IDLE.
        ram[pc + 0] = 0x4E; ram[pc + 1] = 0x72;
        ram[pc + 2] = 0x27; ram[pc + 3] = 0x00;

        // Exception vector table: point every vector (except 0/1, which are
        // reset SSP/PC and must stay) at the MOVE CCR address so any
        // exception lands in the dump epilogue. Mirrors what
        // mame_cpu_capture.lua's start_test() does on the MAME side.
        for (uint32_t v = 2; v < 256; ++v) {
            uint32_t va = v * 4;
            ram[va + 0] = (move_ccr_addr >> 24) & 0xFF;
            ram[va + 1] = (move_ccr_addr >> 16) & 0xFF;
            ram[va + 2] = (move_ccr_addr >>  8) & 0xFF;
            ram[va + 3] = (move_ccr_addr)       & 0xFF;
        }

        // Scratch RAM at $1800.
        auto& init_ram = init["ram"];
        for (unsigned i = 0; i < 64; ++i)
            ram[0x1800 + i] = init_ram[i].get<unsigned>() & 0xFF;

        // Reset + inject all 16 regs.
        top->reset = 1;
        for (int i = 0; i < 32; ++i) tick();
        top->reset = 0;
        for (int r = 0; r < 8; ++r) {
            set_reg(r,     init["d"][r].get<uint32_t>());
            set_reg(8 + r, init["a"][r].get<uint32_t>());
        }

        // Two-stage capture:
        //   (1) First fetch at move_ccr_addr -- the test instruction has
        //       committed enough for PC to advance. Sample PC here; the
        //       Flags register may not have latched yet so SR is captured
        //       at stage (2).
        //   (2) MOVE-CCR write to $1900 -- proves CCR landed in RAM and
        //       Flags is definitely latched. MOVE CCR doesn't modify SR,
        //       so SR sampled here is still the test's output. USP also
        //       sampled here for the same reason.
        bool saw_test_done = false;
        bool saw_ccr_write = false;
        uint32_t got_pc = 0, got_usp = 0;
        uint16_t got_sr = 0;
        for (int cyc = 0; cyc < 5000 && !saw_ccr_write; ++cyc) {
            tick();
            if (!saw_test_done &&
                top->busstate == BS_FETCH &&
                (top->addr_out & 0xFFFFFFFE) == (move_ccr_addr & 0xFFFFFFFE)) {
                saw_test_done = true;
                got_pc = top->pc_out;
            }
            if (top->busstate == BS_WRITE &&
                (top->addr_out & 0xFFFFFFFE) == 0x1900) {
                saw_ccr_write = true;
                got_sr  = top->sr_out;
                got_usp = top->usp_out;
                // A few extra cycles to settle any pending writeback.
                for (int i = 0; i < 16; ++i) tick();
            }
        }

        bool pass = saw_ccr_write;
        std::string fail_reason;
        if (!saw_ccr_write) fail_reason = "timeout (no CCR dump observed)";

        // CCR (with per-test mask: bits cleared in ccr_mask are
        // PRM-undefined for this op and excluded from comparison).
        if (pass) {
            uint8_t mask = spec->ccr_mask;
            uint8_t got  = ram[0x1901] & mask;
            uint8_t exp  = (final_["ccr"].get<unsigned>() & 0xFF) & mask;
            if (got != exp) {
                char buf[96];
                snprintf(buf, sizeof(buf),
                         "CCR: got 0x%02X, expected 0x%02X (mask 0x%02X)",
                         ram[0x1901],
                         final_["ccr"].get<unsigned>() & 0xFF,
                         mask);
                fail_reason = buf; pass = false;
            }
        }
        // D regs
        for (int r = 0; r < 8 && pass; ++r) {
            uint32_t got = get_reg(r);
            uint32_t exp = final_["d"][r].get<uint32_t>();
            if (got != exp) {
                char buf[80];
                snprintf(buf, sizeof(buf), "D%d: got 0x%08X, expected 0x%08X",
                         r, got, exp);
                fail_reason = buf; pass = false;
            }
        }
        // A regs
        for (int r = 0; r < 8 && pass; ++r) {
            uint32_t got = get_reg(8 + r);
            uint32_t exp = final_["a"][r].get<uint32_t>();
            if (got != exp) {
                char buf[80];
                snprintf(buf, sizeof(buf), "A%d: got 0x%08X, expected 0x%08X",
                         r, got, exp);
                fail_reason = buf; pass = false;
            }
        }
        // PC / SR / USP -- gated on corpus field presence so the old
        // schema (no pc/sr/usp) still runs without false negatives.
        //
        // PC: the MAME oracle and this bench use different program layouts
        // (MAME plants preload + dump epilogues; we plant minimal
        // MOVE-CCR + test + MOVE-CCR-out + STOP). Comparing absolute PC
        // is meaningless. The corpus is constructed so every test
        // converges on `test_start + test_len` (Bcc layouts use BRA to
        // merge taken/not-taken paths), so we compare deltas:
        //   expected_pc_here = our_test_start + (corpus.final.pc - corpus.initial.pc)
        if (pass && saw_test_done && final_.contains("pc") && init.contains("pc")) {
            uint32_t corpus_delta =
                final_["pc"].get<uint32_t>() - init["pc"].get<uint32_t>();
            uint32_t exp_pc = 0x1004 + corpus_delta;  // our test_start = 0x1004
            if (got_pc != exp_pc) {
                char buf[96];
                snprintf(buf, sizeof(buf),
                         "PC: got 0x%08X, expected 0x%08X (delta %u)",
                         got_pc, exp_pc, corpus_delta);
                fail_reason = buf; pass = false;
            }
        }
        if (pass && saw_ccr_write && final_.contains("sr")) {
            // Two masks combined:
            //   - IPL (bits 8-10): TG68K resets with IPL=7, MAME with
            //     different default. Tests don't generate interrupts, so
            //     this is a setup-convention difference.
            //   - ccr_mask (bits 0-4): per-test PRM-undefined CCR bits
            //     (e.g. V flag for ABCD/NBCD; N/Z for DIVS overflow).
            //     Mirrors the byte-CCR check above so SR doesn't false-
            //     fire on bits we already exclude.
            uint16_t mask = uint16_t(~uint16_t(0x0700));   // strip IPL
            mask = (mask & uint16_t(0xFFE0)) | uint16_t(spec->ccr_mask & 0x1F);
            uint16_t got_m = got_sr & mask;
            uint16_t exp_m =
                uint16_t(final_["sr"].get<uint32_t>()) & mask;
            if (got_m != exp_m) {
                char buf[112];
                snprintf(buf, sizeof(buf),
                         "SR: got 0x%04X, expected 0x%04X "
                         "(IPL+ccr_mask=0x%04X)",
                         got_sr & uint16_t(~uint16_t(0x0700)),
                         uint16_t(final_["sr"].get<uint32_t>()) & uint16_t(~uint16_t(0x0700)),
                         mask);
                fail_reason = buf; pass = false;
            }
        }
        if (pass && saw_test_done && final_.contains("usp")) {
            uint32_t exp_usp = final_["usp"].get<uint32_t>();
            if (got_usp != exp_usp) {
                char buf[80];
                snprintf(buf, sizeof(buf),
                         "USP: got 0x%08X, expected 0x%08X", got_usp, exp_usp);
                fail_reason = buf; pass = false;
            }
        }
        // Scratch RAM
        for (int i = 0; i < 64 && pass; ++i) {
            uint8_t got = ram[0x1800 + i];
            uint8_t exp = final_["ram"][i].get<unsigned>() & 0xFF;
            if (got != exp) {
                char buf[80];
                snprintf(buf, sizeof(buf),
                         "ram[%d] (@$%04X): got 0x%02X, expected 0x%02X",
                         i, 0x1800 + i, got, exp);
                fail_reason = buf; pass = false;
            }
        }

        if (pass) {
            ++passed;
        } else {
            ++failed;
            std::cerr << "FAIL " << name << ": " << fail_reason << "\n";
            std::cerr << "  instr: " << disasm_at(0x1004) << "\n";
        }
    }
    std::cerr << "\n" << passed << " passed, " << failed << " failed, "
              << skipped << " skipped in " << fname << "\n";
    finish();
    return failed ? 1 : 0;
}
